name: 'github-extract-task-ids-action'
description: 'Extract task ids from the branch name, the pull request title and the changelog links in the body, using regular expressions'
author: 'Tjitse-E'
runs:
    using: 'node24'
    main: 'dist/index.cjs'
inputs:
    token:
        description: Your Github token
        required: true
    task_id_pattern:
        description: The regex patteren of your task id
        required: true
        default: '[A-Z]{2,}-[0-9]{1,5}'
    pull_number:
        description: The pull request number
        required: false
