name: 'github-extract-task-ids-action'
description: 'Extract task ids from commit messages, branch and pull request title using regular expressions'
author: 'Tjitse-E'
runs:
    using: 'node12'
    main: 'dist/index.js'
inputs:
    token:
        description: Your Github token
        required: true
    task_id_pattern:
        description: The regex patteren of your task id
        required: true
        default: '[A-Z]{2,}-[0-9]{1,5}'

