name: Tests

on:
  push:
  pull_request:

permissions: {}

jobs:
  test:
    runs-on: runs-on=${{ github.run_id }}/runner=micro/spot=lp
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
